# Generated by Django 3.1.7 on 2021-03-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, verbose_name='user_email')),
                ('first_name_kr', models.CharField(max_length=8, verbose_name='first_name_kr')),
                ('last_name_kr', models.CharField(max_length=32, verbose_name='last_name_kr')),
                ('first_name_en', models.CharField(max_length=32, verbose_name='first_name_en')),
                ('last_name_en', models.CharField(max_length=32, verbose_name='last_name_en')),
                ('user_password', models.CharField(max_length=64, verbose_name='user_passwd')),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='Register_date')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
