# Generated by Django 3.1.7 on 2021-03-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=512, verbose_name='user_passwd'),
        ),
    ]
