# Generated by Django 3.2.2 on 2021-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preservedResult',
            fields=[
                ('result_seq', models.AutoField(primary_key=True, serialize=False)),
                ('owner_email', models.EmailField(max_length=254, verbose_name='user_email')),
                ('owner_last_name_kr', models.CharField(max_length=32, verbose_name='last_name_kr')),
                ('result_path', models.TextField()),
                ('preserve_dttm', models.DateField(auto_now_add=True, verbose_name='preserve_date')),
            ],
        ),
    ]
