# Generated by Django 3.2.2 on 2021-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preservedresult',
            name='alpha_path',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='preservedresult',
            name='result_path',
            field=models.TextField(default=None),
        ),
    ]
