# Generated by Django 3.2.2 on 2021-05-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signMaker', '0002_auto_20210515_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='preservedWatermark',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('owner_email', models.EmailField(max_length=254, verbose_name='user_email')),
                ('owner_last_name_kr', models.CharField(max_length=32, verbose_name='last_name_kr')),
                ('image', models.ImageField(upload_to='preservedWatermark/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='watermark_result_upload_date')),
            ],
        ),
        migrations.AlterField(
            model_name='preservedresult',
            name='preserve_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='preserve_date'),
        ),
    ]
