# Generated by Django 3.2.2 on 2021-05-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signMaker', '0003_auto_20210516_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preservedwatermark',
            name='image',
        ),
        migrations.AddField(
            model_name='preservedwatermark',
            name='result_path',
            field=models.TextField(default=None),
        ),
    ]
