# Generated by Django 3.2.2 on 2021-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signMaker', '0004_auto_20210516_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='preservedresult',
            name='is_removed',
            field=models.TextField(default='N'),
        ),
        migrations.AddField(
            model_name='preservedresult',
            name='is_rep',
            field=models.TextField(default='N'),
        ),
    ]
