# Generated by Django 3.2.2 on 2021-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signMaker', '0005_auto_20210606_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preservedresult',
            name='is_removed',
            field=models.TextField(default='F'),
        ),
        migrations.AlterField(
            model_name='preservedresult',
            name='is_rep',
            field=models.TextField(default='F'),
        ),
    ]
